# Generated by Django 5.2.14 on 2026-08-23 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Select a partner for 50/50 splits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
