# Generated by Django 5.2.14 on 2026-08-31 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='legal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransactionLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('transaction_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'label')},
            },
        ),
    ]
